server:
  port: 8025
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp  
  
  datasource: # Mybatis dataSource DB 연결
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ccibfzyyg2bg.us-west-1.rds.amazonaws.com/tLogDB?characterEncoding=utf-8
    username: admin
    password: tlogadmin
  
  devtools: # 서버 자동 시작
    livereload:
      enabled: true
 
  servlet: # multipart 설정
    multipart:
      enabled: true
      max-file-size: 20MB
      
mybatis: 
  #mybatis에서 팩키지 생략 할 수 있도록 설정
  type-aliases-package: com.tworaveler.tlog
  mapper-locations: mapper/*Mapper.xml

# 업로드나중에 쓸 중요한 자산
#upload-path : /upload/**
#resource-path : file:///home/ubuntu/TLOG/upload/
#prefix-path : /home/ubuntu/TLOG/upload/
#logout-path : http://tlog0609.kro.kr